import {
  faArrowRight,
  faBullhorn,
  faScaleBalanced,
  faGear,
  faCoins,
  faPenRuler,
  faDiagramProject,
  faCircleQuestion,
  faQuoteLeft,
  faCheck,
  faChevronDown,
  faCube,
  faGripVertical,
  faLanguage,
  faUsers,
  faCodeBranch,
  faPalette,
  faBolt,
  faRocket,
  faLayerGroup,
  faMoon,
  faSun,
  faWrench,
  faPencil,
  faGlobe,
  faHighlighter,
  faLink,
  faList,
  faCheckCircle,
  faCalendar,
  faArrowUp,
  faArrowDown,
  faTrash,
  faPlus,
  faSave,
  faCircleExclamation,
  faEnvelope,
  faShareNodes,
  faLocationDot,
  faPhone,
  faBrain,
  faWandMagicSparkles,
  faGauge,
  faBarsProgress,
  faTurnUp,
  faSearch,
  faCircleInfo,
  faDownload,
  faSpinner,
  faXmark,
  faPuzzlePiece,
  faTags,
  faDatabase,
  faClock,
  faMicrochip,
  faChevronUp,
  faTerminal,
  faChevronLeft,
  faChevronRight,
} from '@fortawesome/free-solid-svg-icons'
import {
  faFacebookF,
  faXTwitter,
  faLinkedinIn,
  faInstagram,
  faYoutube,
} from '@fortawesome/free-brands-svg-icons'

export const iconOptions = [
  // Solid Icons
  { name: 'arrow-right', label: 'Arrow Right', icon: faArrowRight },
  { name: 'bullhorn', label: 'Bullhorn', icon: faBullhorn },
  { name: 'scale-balanced', label: 'Scale Balanced', icon: faScaleBalanced },
  { name: 'gear', label: 'Gear', icon: faGear },
  { name: 'coins', label: 'Coins', icon: faCoins },
  { name: 'pen-ruler', label: 'Pen Ruler', icon: faPenRuler },
  { name: 'diagram-project', label: 'Diagram Project', icon: faDiagramProject },
  { name: 'circle-question', label: 'Circle Question', icon: faCircleQuestion },
  { name: 'quote-left', label: 'Quote Left', icon: faQuoteLeft },
  { name: 'check', label: 'Check', icon: faCheck },
  { name: 'chevron-down', label: 'Chevron Down', icon: faChevronDown },
  { name: 'cube', label: 'Cube', icon: faCube },
  { name: 'grip-vertical', label: 'Grip Vertical', icon: faGripVertical },
  { name: 'language', label: 'Language', icon: faLanguage },
  { name: 'users', label: 'Users', icon: faUsers },
  { name: 'code-branch', label: 'Code Branch', icon: faCodeBranch },
  { name: 'palette', label: 'Palette', icon: faPalette },
  { name: 'bolt', label: 'Bolt', icon: faBolt },
  { name: 'rocket', label: 'Rocket', icon: faRocket },
  { name: 'layer-group', label: 'Layer Group', icon: faLayerGroup },
  { name: 'moon', label: 'Moon', icon: faMoon },
  { name: 'sun', label: 'Sun', icon: faSun },
  { name: 'wrench', label: 'Wrench', icon: faWrench },
  { name: 'pencil', label: 'Pencil', icon: faPencil },
  { name: 'globe', label: 'Globe', icon: faGlobe },
  { name: 'highlighter', label: 'Highlighter', icon: faHighlighter },
  { name: 'link', label: 'Link', icon: faLink },
  { name: 'list', label: 'List', icon: faList },
  { name: 'check-circle', label: 'Check Circle', icon: faCheckCircle },
  { name: 'calendar', label: 'Calendar', icon: faCalendar },
  { name: 'arrow-up', label: 'Arrow Up', icon: faArrowUp },
  { name: 'arrow-down', label: 'Arrow Down', icon: faArrowDown },
  { name: 'trash', label: 'Trash', icon: faTrash },
  { name: 'plus', label: 'Plus', icon: faPlus },
  { name: 'save', label: 'Save', icon: faSave },
  { name: 'circle-exclamation', label: 'Circle Exclamation', icon: faCircleExclamation },
  { name: 'envelope', label: 'Envelope', icon: faEnvelope },
  { name: 'share-nodes', label: 'Share Nodes', icon: faShareNodes },
  { name: 'location-dot', label: 'Location Dot', icon: faLocationDot },
  { name: 'phone', label: 'Phone', icon: faPhone },
  { name: 'brain', label: 'Brain', icon: faBrain },
  { name: 'wand-magic-sparkles', label: 'Magic Wand', icon: faWandMagicSparkles },
  { name: 'gauge', label: 'Gauge', icon: faGauge },
  { name: 'bars-progress', label: 'Bars Progress', icon: faBarsProgress },
  { name: 'turn-up', label: 'Turn Up', icon: faTurnUp },
  { name: 'search', label: 'Search', icon: faSearch },
  { name: 'circle-info', label: 'Circle Info', icon: faCircleInfo },
  { name: 'download', label: 'Download', icon: faDownload },
  { name: 'spinner', label: 'Spinner', icon: faSpinner },
  { name: 'xmark', label: 'X-Mark', icon: faXmark },
  { name: 'puzzle-piece', label: 'Puzzle Piece', icon: faPuzzlePiece },
  { name: 'tags', label: 'Tags', icon: faTags },
  { name: 'database', label: 'Database', icon: faDatabase },
  { name: 'clock', label: 'Clock', icon: faClock },
  { name: 'microchip', label: 'Microchip', icon: faMicrochip },
  { name: 'chevron-up', label: 'Chevron Up', icon: faChevronUp },
  { name: 'terminal', label: 'Terminal', icon: faTerminal },
  { name: 'chevron-left', label: 'Chevron Left', icon: faChevronLeft },
  { name: 'chevron-right', label: 'Chevron Right', icon: faChevronRight },

  // Brand Icons
  { name: 'facebook-f', label: 'Facebook', icon: faFacebookF },
  { name: 'x-twitter', label: 'X (Twitter)', icon: faXTwitter },
  { name: 'linkedin-in', label: 'LinkedIn', icon: faLinkedinIn },
  { name: 'instagram', label: 'Instagram', icon: faInstagram },
  { name: 'youtube', label: 'YouTube', icon: faYoutube },
] as const

export const iconMap: Record<string, any> = iconOptions.reduce(
  (acc, item) => {
    acc[item.name] = item.icon
    return acc
  },
  {} as Record<string, any>
)
